# Generated by Django 5.1.4 on 2024-12-09 20:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Planes', '0003_rename_max_propiedades_planinmuebles_max_inmuebles'),
        ('Prestamos', '0002_perfilagenteprestamos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerfilAgentePrestamos',
            new_name='PerfilAgenteHipotecario',
        ),
    ]
