# Generated by Django 5.1.4 on 2024-12-09 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0007_comentario_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='Prestamos.evaluacioncrediticia'),
        ),
    ]
