# Generated by Django 5.1.4 on 2024-12-10 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0009_rename_usuario_perfilprestatarioprefab_dueño'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilprestatarioprefab',
            name='dueño',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefabs_perfiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
