# Generated by Django 5.1.4 on 2024-12-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0010_alter_perfilprestatarioprefab_dueño'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprestatarioprefab',
            name='nombre',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
