# Generated by Django 5.1.4 on 2024-12-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0012_alter_documentoevaluacionprefab_perfil_prefab'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprestatarioprefab',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
