# Generated by Django 5.1.4 on 2024-12-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0014_preguntaperfil_respuestaperfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidadbancaria',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='estadoevaluacion',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='etapaevaluacion',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='preguntaperfil',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='respuestaperfil',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
