# Generated by Django 5.1.4 on 2024-12-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0015_alter_entidadbancaria_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaperfil',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='respuestaperfil',
            unique_together={('pregunta', 'nombre')},
        ),
    ]
