# Generated by Django 5.1.4 on 2024-12-11 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0016_alter_respuestaperfil_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestaperfil',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='Prestamos.preguntaperfil'),
        ),
    ]
