# Generated by Django 5.1.4 on 2024-12-11 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0005_inmueble_num_visitas_delete_visita'),
        ('Prestamos', '0017_alter_respuestaperfil_pregunta'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprestatario',
            name='inmueble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestatarios', to='Inmuebles.inmueble'),
        ),
    ]
