# Generated by Django 5.1.4 on 2024-12-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0019_evaluacioncrediticia_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacioncrediticia',
            name='fecha_fin_estimada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacioncrediticia',
            name='fecha_fin_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluacioncrediticia',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
