# Generated by Django 5.1.4 on 2024-12-16 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0020_evaluacioncrediticia_fecha_fin_estimada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Prestamos.evaluacioncrediticia'),
        ),
    ]
