# Generated by Django 5.1.4 on 2024-12-17 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0021_alter_comentario_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadoevaluacion',
            name='is_system_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evaluacioncrediticia',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Prestamos.estadoevaluacion'),
        ),
    ]
