# Generated by Django 5.1.2 on 2024-11-11 15:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ubicacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubTipoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAntiguedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(100)])),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('habitaciones', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('baños', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('pisos', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('ascensores', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('estacionamientos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('area_construida', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('precio_soles', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('precio_dolares', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('mantenimiento', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('años', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('caracteristicas', models.ManyToManyField(blank=True, to='Inmuebles.caracteristica')),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inmuebles.estado')),
                ('subtipo_Inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Inmuebles.subtipoinmueble')),
                ('tipo_antiguedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Inmuebles.tipoantiguedad')),
                ('tipo_Inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Inmuebles.tipoinmueble')),
                ('tipo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inmuebles.tipooperacion')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(upload_to='Inmueblees/')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('portada', models.BooleanField(default=False)),
                ('Inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='Inmuebles.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='PlanoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.ImageField(upload_to='planos/')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('Inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='Inmuebles.inmueble')),
            ],
        ),
        migrations.AddField(
            model_name='subtipoinmueble',
            name='tipo_Inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inmuebles.tipoinmueble'),
        ),
        migrations.CreateModel(
            name='UbicacionInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle_numero', models.CharField(max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('Inmueble', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion', to='Inmuebles.inmueble')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ubicacion.distrito')),
            ],
        ),
    ]
