# Generated by Django 5.1.2 on 2024-11-11 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estado',
            new_name='EstadoInmueble',
        ),
        migrations.RenameField(
            model_name='imageninmueble',
            old_name='Inmueble',
            new_name='inmueble',
        ),
        migrations.RenameField(
            model_name='imageninmueble',
            old_name='portada',
            new_name='is_portada',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='subtipo_Inmueble',
            new_name='subtipo_inmueble',
        ),
        migrations.RenameField(
            model_name='inmueble',
            old_name='tipo_Inmueble',
            new_name='tipo_inmueble',
        ),
        migrations.RenameField(
            model_name='planoinmueble',
            old_name='Inmueble',
            new_name='inmueble',
        ),
        migrations.RenameField(
            model_name='subtipoinmueble',
            old_name='tipo_Inmueble',
            new_name='tipo_inmueble',
        ),
        migrations.RenameField(
            model_name='ubicacioninmueble',
            old_name='calle_numero',
            new_name='calle',
        ),
        migrations.RenameField(
            model_name='ubicacioninmueble',
            old_name='Inmueble',
            new_name='inmueble',
        ),
        migrations.AddField(
            model_name='ubicacioninmueble',
            name='numero',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageninmueble',
            name='imagen',
            field=models.ImageField(upload_to='inmuebles/'),
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='Inmuebles.inmueble')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='Inmuebles.inmueble')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
