# Generated by Django 5.1.2 on 2024-11-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0002_rename_estado_estadoinmueble_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caracteristica',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
