# Generated by Django 5.1.2 on 2024-11-26 20:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0003_alter_caracteristica_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'inmueble')},
        ),
    ]
