# Generated by Django 5.1.2 on 2024-11-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inmuebles', '0004_alter_favorito_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='num_visitas',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Visita',
        ),
    ]
