# Generated by Django 5.1.2 on 2024-11-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Planes', '0002_remove_planprestamos_max_empleados'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planinmuebles',
            old_name='max_propiedades',
            new_name='max_inmuebles',
        ),
    ]
