# Generated by Django 5.1.2 on 2024-11-04 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0001_initial'),
        ('Usuarios', '0002_alter_usuario_apellidos_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilagenteprestamos',
            name='entidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Prestamos.entidadbancaria'),
            preserve_default=False,
        ),
    ]
