# Generated by Django 5.1.2 on 2024-11-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_authprovider_tipocliente_alter_usuario_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilagenteprestamos',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='perfilcliente',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='perfilempleadoinmobiliaria',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='perfilparticularinmuebles',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='perfilprofesionalservicios',
            name='dni',
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(default=12345678, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
