# Generated by Django 5.1.2 on 2024-11-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_remove_perfilagenteprestamos_dni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='provider',
        ),
    ]
