# Generated by Django 5.1.2 on 2024-11-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0006_remove_usuario_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='Usuarios.authprovider'),
        ),
    ]
