# Generated by Django 5.1.2 on 2024-11-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0008_alter_usuario_dni'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoCliente',
            new_name='TipoUsuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo_cliente',
            new_name='tipo_usuario',
        ),
    ]
