# Generated by Django 5.1.2 on 2024-11-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0009_rename_tipocliente_tipousuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='provider',
        ),
        migrations.AddField(
            model_name='usuario',
            name='provider',
            field=models.ManyToManyField(null=True, related_name='usuarios', to='Usuarios.authprovider'),
        ),
    ]
