# Generated by Django 5.1.2 on 2024-11-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0010_remove_usuario_provider_usuario_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ManyToManyField(null=True, related_name='usuarios', to='Usuarios.tipousuario'),
        ),
    ]
