# Generated by Django 5.1.2 on 2024-11-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0011_remove_usuario_tipo_usuario_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='provider',
            field=models.ManyToManyField(related_name='usuarios', to='Usuarios.authprovider'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ManyToManyField(related_name='usuarios', to='Usuarios.tipousuario'),
        ),
    ]
