# Generated by Django 5.1.2 on 2024-12-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0014_perfilparticularinmuebles_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempleadoinmobiliaria',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner/empleados'),
        ),
        migrations.AddField(
            model_name='perfilinmobiliaria',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner/inmobiliarias'),
        ),
        migrations.AddField(
            model_name='perfilparticularinmuebles',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner/particulares'),
        ),
    ]
